/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121755-g41a9c6ec5f-20251114"
#endif /* AVUTIL_FFVERSION_H */
